#include <gtest/gtest.h>
#include <sstream>
#include "unicode_char.h"

TEST(BidirectionalCategoryGenTest, test_cats) {
    std::stringstream ss;
    EXPECT_EQ(unicode::BidirectionalCategory::BN, unicode::getBidirectionalCategory(0x0000));
    ss << unicode::BidirectionalCategory::BN;
    EXPECT_EQ("BN", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::S, unicode::getBidirectionalCategory(0x0009));
    ss << unicode::BidirectionalCategory::S;
    EXPECT_EQ("S", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::B, unicode::getBidirectionalCategory(0x000A));
    ss << unicode::BidirectionalCategory::B;
    EXPECT_EQ("B", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::WS, unicode::getBidirectionalCategory(0x000C));
    ss << unicode::BidirectionalCategory::WS;
    EXPECT_EQ("WS", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::ON, unicode::getBidirectionalCategory(0x0021));
    ss << unicode::BidirectionalCategory::ON;
    EXPECT_EQ("ON", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::ET, unicode::getBidirectionalCategory(0x0023));
    ss << unicode::BidirectionalCategory::ET;
    EXPECT_EQ("ET", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::ES, unicode::getBidirectionalCategory(0x002B));
    ss << unicode::BidirectionalCategory::ES;
    EXPECT_EQ("ES", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::CS, unicode::getBidirectionalCategory(0x002C));
    ss << unicode::BidirectionalCategory::CS;
    EXPECT_EQ("CS", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::EN, unicode::getBidirectionalCategory(0x0030));
    ss << unicode::BidirectionalCategory::EN;
    EXPECT_EQ("EN", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::L, unicode::getBidirectionalCategory(0x0041));
    ss << unicode::BidirectionalCategory::L;
    EXPECT_EQ("L", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::NSM, unicode::getBidirectionalCategory(0x0300));
    ss << unicode::BidirectionalCategory::NSM;
    EXPECT_EQ("NSM", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::R, unicode::getBidirectionalCategory(0x05BE));
    ss << unicode::BidirectionalCategory::R;
    EXPECT_EQ("R", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::AN, unicode::getBidirectionalCategory(0x0600));
    ss << unicode::BidirectionalCategory::AN;
    EXPECT_EQ("AN", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::AL, unicode::getBidirectionalCategory(0x0608));
    ss << unicode::BidirectionalCategory::AL;
    EXPECT_EQ("AL", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::LRE, unicode::getBidirectionalCategory(0x202A));
    ss << unicode::BidirectionalCategory::LRE;
    EXPECT_EQ("LRE", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::RLE, unicode::getBidirectionalCategory(0x202B));
    ss << unicode::BidirectionalCategory::RLE;
    EXPECT_EQ("RLE", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::PDF, unicode::getBidirectionalCategory(0x202C));
    ss << unicode::BidirectionalCategory::PDF;
    EXPECT_EQ("PDF", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::LRO, unicode::getBidirectionalCategory(0x202D));
    ss << unicode::BidirectionalCategory::LRO;
    EXPECT_EQ("LRO", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::RLO, unicode::getBidirectionalCategory(0x202E));
    ss << unicode::BidirectionalCategory::RLO;
    EXPECT_EQ("RLO", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::LRI, unicode::getBidirectionalCategory(0x2066));
    ss << unicode::BidirectionalCategory::LRI;
    EXPECT_EQ("LRI", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::RLI, unicode::getBidirectionalCategory(0x2067));
    ss << unicode::BidirectionalCategory::RLI;
    EXPECT_EQ("RLI", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::FSI, unicode::getBidirectionalCategory(0x2068));
    ss << unicode::BidirectionalCategory::FSI;
    EXPECT_EQ("FSI", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BidirectionalCategory::PDI, unicode::getBidirectionalCategory(0x2069));
    ss << unicode::BidirectionalCategory::PDI;
    EXPECT_EQ("PDI", ss.str());
    ss.str("");
    ss.clear();
}
