#include <gtest/gtest.h>
#include <sstream>
#include "unicode_char.h"

TEST(GeneralCategoryGenTest, test_cats) {
    std::stringstream ss;
    EXPECT_EQ(unicode::GeneralCategory::Cc, unicode::getGeneralCategory(0x0000));
    ss << unicode::GeneralCategory::Cc;
    EXPECT_EQ("Cc", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Zs, unicode::getGeneralCategory(0x0020));
    ss << unicode::GeneralCategory::Zs;
    EXPECT_EQ("Zs", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Po, unicode::getGeneralCategory(0x0021));
    ss << unicode::GeneralCategory::Po;
    EXPECT_EQ("Po", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Sc, unicode::getGeneralCategory(0x0024));
    ss << unicode::GeneralCategory::Sc;
    EXPECT_EQ("Sc", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Ps, unicode::getGeneralCategory(0x0028));
    ss << unicode::GeneralCategory::Ps;
    EXPECT_EQ("Ps", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Pe, unicode::getGeneralCategory(0x0029));
    ss << unicode::GeneralCategory::Pe;
    EXPECT_EQ("Pe", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Sm, unicode::getGeneralCategory(0x002B));
    ss << unicode::GeneralCategory::Sm;
    EXPECT_EQ("Sm", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Pd, unicode::getGeneralCategory(0x002D));
    ss << unicode::GeneralCategory::Pd;
    EXPECT_EQ("Pd", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Nd, unicode::getGeneralCategory(0x0030));
    ss << unicode::GeneralCategory::Nd;
    EXPECT_EQ("Nd", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Lu, unicode::getGeneralCategory(0x0041));
    ss << unicode::GeneralCategory::Lu;
    EXPECT_EQ("Lu", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Sk, unicode::getGeneralCategory(0x005E));
    ss << unicode::GeneralCategory::Sk;
    EXPECT_EQ("Sk", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Pc, unicode::getGeneralCategory(0x005F));
    ss << unicode::GeneralCategory::Pc;
    EXPECT_EQ("Pc", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Ll, unicode::getGeneralCategory(0x0061));
    ss << unicode::GeneralCategory::Ll;
    EXPECT_EQ("Ll", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::So, unicode::getGeneralCategory(0x00A6));
    ss << unicode::GeneralCategory::So;
    EXPECT_EQ("So", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Lo, unicode::getGeneralCategory(0x00AA));
    ss << unicode::GeneralCategory::Lo;
    EXPECT_EQ("Lo", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Pi, unicode::getGeneralCategory(0x00AB));
    ss << unicode::GeneralCategory::Pi;
    EXPECT_EQ("Pi", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Cf, unicode::getGeneralCategory(0x00AD));
    ss << unicode::GeneralCategory::Cf;
    EXPECT_EQ("Cf", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::No, unicode::getGeneralCategory(0x00B2));
    ss << unicode::GeneralCategory::No;
    EXPECT_EQ("No", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Pf, unicode::getGeneralCategory(0x00BB));
    ss << unicode::GeneralCategory::Pf;
    EXPECT_EQ("Pf", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Lt, unicode::getGeneralCategory(0x01C5));
    ss << unicode::GeneralCategory::Lt;
    EXPECT_EQ("Lt", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Lm, unicode::getGeneralCategory(0x02B0));
    ss << unicode::GeneralCategory::Lm;
    EXPECT_EQ("Lm", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Mn, unicode::getGeneralCategory(0x0300));
    ss << unicode::GeneralCategory::Mn;
    EXPECT_EQ("Mn", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Me, unicode::getGeneralCategory(0x0488));
    ss << unicode::GeneralCategory::Me;
    EXPECT_EQ("Me", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Mc, unicode::getGeneralCategory(0x0903));
    ss << unicode::GeneralCategory::Mc;
    EXPECT_EQ("Mc", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Nl, unicode::getGeneralCategory(0x16EE));
    ss << unicode::GeneralCategory::Nl;
    EXPECT_EQ("Nl", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Zl, unicode::getGeneralCategory(0x2028));
    ss << unicode::GeneralCategory::Zl;
    EXPECT_EQ("Zl", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Zp, unicode::getGeneralCategory(0x2029));
    ss << unicode::GeneralCategory::Zp;
    EXPECT_EQ("Zp", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Cs, unicode::getGeneralCategory(0xD800));
    ss << unicode::GeneralCategory::Cs;
    EXPECT_EQ("Cs", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::GeneralCategory::Co, unicode::getGeneralCategory(0xE000));
    ss << unicode::GeneralCategory::Co;
    EXPECT_EQ("Co", ss.str());
    ss.str("");
    ss.clear();
}

TEST(GeneralCategoryGenTest, test_base_cats) {
    std::stringstream ss;
    EXPECT_EQ(unicode::BaseGeneralCategory::C, unicode::getBaseGeneralCategory(0x0000));
    ss << unicode::BaseGeneralCategory::C;
    EXPECT_EQ("C", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BaseGeneralCategory::Z, unicode::getBaseGeneralCategory(0x0020));
    ss << unicode::BaseGeneralCategory::Z;
    EXPECT_EQ("Z", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BaseGeneralCategory::P, unicode::getBaseGeneralCategory(0x0021));
    ss << unicode::BaseGeneralCategory::P;
    EXPECT_EQ("P", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BaseGeneralCategory::S, unicode::getBaseGeneralCategory(0x0024));
    ss << unicode::BaseGeneralCategory::S;
    EXPECT_EQ("S", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BaseGeneralCategory::N, unicode::getBaseGeneralCategory(0x0030));
    ss << unicode::BaseGeneralCategory::N;
    EXPECT_EQ("N", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BaseGeneralCategory::L, unicode::getBaseGeneralCategory(0x0041));
    ss << unicode::BaseGeneralCategory::L;
    EXPECT_EQ("L", ss.str());
    ss.str("");
    ss.clear();
    EXPECT_EQ(unicode::BaseGeneralCategory::M, unicode::getBaseGeneralCategory(0x0300));
    ss << unicode::BaseGeneralCategory::M;
    EXPECT_EQ("M", ss.str());
    ss.str("");
    ss.clear();
}
