#!/usr/bin/env bash
# ./get_data.sh
python gen_header_open.py
python gen_code_value.py
python gen_general_category.py
python gen_canonical_combining_class.py
python gen_bidirectional_category.py
python gen_decomposition_mapping.py
python gen_numeric.py
python gen_mirrored.py
python gen_cases.py
python gen_manual.py
python gen_header_close.py
