name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: python -m pip install --upgrade pip && python -m pip install pycodestyle cpplint
    - name: python lint
      run: python -m pycodestyle --max-line-length=120 script/*.py
    - name: c++ lint
      run: python -m cpplint --linelength=120 --filter=-build/include_subdir include/*.h src/*.cpp tests/*.cpp
